Young-Artists/Young-Artists/Models/Commodity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace Young_Artists.Models
{
    public partial class Commodity
    {
        public int Id { get; set; }
        [DisplayName("商品名稱 ")]
        public string? CommodityName { get; set; }
        [DisplayName("商品敘述 ")]
        public string? CommodityNarrative { get; set; }
        [DisplayName("商品庫存 ")]
        public int? CommodityNum { get; set; }
        [DisplayName("商品價格 ")]
        public decimal? CommodityPrice { get; set; }
        [DisplayName("商品圖片 ")]
        public string? CommodityImage { get; set; }


        [DisplayName("商品排序 ")]
        public int? CommoditySort { get; set; }
        [DisplayName("商品銷售量 ")]
        public int? CommoditySale { get; set; }
        [DisplayName("商品上架時間 ")]
        public string? CommodityStart { get; set; }
        [DisplayName("商品分類 ")]
        public string? CommodityClassification { get; set; }
        [DisplayName("商品上下架 ")]
        public bool? CommodityState { get; set; }
    }
}

Young-Artists/Young-Artists/Controllers/CommodityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing.Printing;
using X.PagedList;
using Young_Artists.Models;
using Young_Artists.ViewModel;

namespace Young_Artists.Controllers
{

    //商品表
    public class CommodityController : Controller
    {
        IWebHostEnvironment _environment;
        public CommodityController(IWebHostEnvironment environment)
        {
            _environment = environment;
        }

        public IActionResult Index(int page = 1, int pageSize = 3)
        {
            IPagedList<Commodity> datas = null;
            YoungArtistsContext db = new YoungArtistsContext();
            //datas = from t in db.Commodities
            //        select t;
            //var datas = db.Commodities.AsQueryable();
            var currentPage = page < 1 ? 1 : page;
            var results = db.Commodities.ToPagedList(page, pageSize);
            return View(results);
            //return View();
        }

        //public IActionResult List()
        //{
        //    IEnumerable<Commodity> datas = null;
        //    YoungArtistsContext db = new YoungArtistsContext();
        //    datas = from t in db.Commodities
        //            select t;

        //    return View(datas);
        //}
        //int page = 1, int pageSize = 3
        //public IActionResult List(int page =1)
        //{
        //    IPagedList<Commodity> datas = null;
        //    YoungArtistsContext db = new YoungArtistsContext();
        //    //datas = from t in db.Commodities
        //    //        select t;
        //    var currentPage = page < 1 ? 1 : page;
        //    var results = db.Commodities.ToPagedList(currentPage, 2);
        //    return View(results);
        //}
        //public IActionResult List(int page = 1, int pageSize =2)
        //{
        //    IPagedList < Commodity > datas = null;
        //    YoungArtistsContext db = new YoungArtistsContext();
        //    //datas = from t in db.Commodities
        //    //        select t;
        //    //var datas = db.Commodities.AsQueryable();
        //    var results = db.Commodities.ToPagedList(page, pageSize);
        //    return View(results);
        //}

        [HttpGet]
        public IActionResult List(string sortCommodity,int page =1 )
        {
            int pageSize = 5;
            ViewBag.SortBy = sortCommodity;
            var currentPage = page < 1 ? 1 : page;
            //IEnumerable<Commodity> datas = null;
            YoungArtistsContext db = new YoungArtistsContext();
            //datas = from t in db.Commodities
            //        select t;
            IPagedList<Commodity> results = null;
            switch (sortCommodity)
            {
                case "UpCommodityName":
                    results = db.Commodities.OrderBy(t=>t.CommodityName).ToList().ToPagedList(currentPage, pageSize);
                    break;
                case "DownCommodityName":
                    //datas = from t in db.Commodities
                    //        orderby t.CommodityName descending
                    //        select t;
                    results = db.Commodities.OrderByDescending(t => t.Id).ToList().ToPagedList(currentPage, pageSize);
                    break;
                case "UpCommodityNum":
                    results = db.Commodities.OrderBy(t => t.CommodityNum).ToList().ToPagedList(currentPage, pageSize);
                    break;
                case "DownCommodityNum":
                    results = db.Commodities.OrderByDescending(t => t.CommodityNum).ToList().ToPagedList(currentPage, pageSize);
                    break;
                case "UpCommodityId":
                    results = db.Commodities.OrderBy(t => t.Id).ToList().ToPagedList(currentPage, pageSize);
                    break;
                case "DownCommodityId":
                    results = db.Commodities.OrderByDescending(t => t.Id).ToList().ToPagedList(currentPage, pageSize);
                    break;
                case "UpCommodityPrice":
                    results = db.Commodities.OrderBy(t => t.CommodityPrice).ToList().ToPagedList(currentPage, pageSize);
                    break;
                case "DownCommodityPrice":
                    results = db.Commodities.OrderByDescending(t => t.CommodityPrice).ToList().ToPagedList(currentPage, pageSize);
                    break;
                case "UpCommodityStart":
                    results = db.Commodities.OrderBy(t => t.CommodityStart).ToList().ToPagedList(currentPage, pageSize);
                    break;
                case "DownCommodityStart":
                    results = db.Commodities.OrderByDescending(t => t.CommodityStart).ToList().ToPagedList(currentPage, pageSize);
                    break;
                case "UpCommodityState":
                    results = db.Commodities.OrderByDescending(t => t.CommodityState).ToList().ToPagedList(currentPage, pageSize);
                    break;
                case "DownCommodityState":
                    results = db.Commodities.OrderBy(t => t.CommodityState).ToList().ToPagedList(currentPage, pageSize);
                    break;
                default:
                    results = db.Commodities.ToList().ToPagedList(currentPage, pageSize);
                    break;

            }
            return View(results);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CCommodityViewModel vm)
        {
            YoungArtistsContext db = new YoungArtistsContext();
            Commodity x = new Commodity();
            if (x != null)
            {
                if (vm.photo != null)
                {
                    string fileExtension = System.IO.Path.GetExtension(vm.photo.FileName);
                    string photoName = Guid.NewGuid().ToString() + fileExtension;
                    string path = _environment.WebRootPath + "/Images/" + photoName;
                    x.CommodityImage = photoName;
                    vm.photo.CopyTo(new FileStream(path, FileMode.Create));
                }
                x.CommodityName = vm.CommodityName;
                x.CommodityNarrative = vm.CommodityNarrative;
                x.CommodityNum = vm.CommodityNum;
                x.CommodityStart = DateTime.Now.ToString();
                //x.CommodityStart = vm.CommodityStart;
                x.CommodityPrice = vm.CommodityPrice;
                x.CommodityClassification = vm.CommodityClassification;
                x.CommodityState = vm.CommodityState;
                db.Commodities.Add(x);
                db.SaveChangesAsync();
            }
            return RedirectToAction("List");
        }
        public IActionResult Delete(int? id)
        {
            YoungArtistsContext db = new YoungArtistsContext();
            Commodity delCommodity = db.Commodities.FirstOrDefault(c => c.Id== id);
            if(delCommodity != null)
            {
                db.Commodities.Remove(delCommodity);
                db.SaveChangesAsync();
            }
            return RedirectToAction("List");
        }
        public IActionResult Edit(int? id)
        {
            if (id != null)
            {
                YoungArtistsContext db = new YoungArtistsContext();
                Commodity x = db.Commodities.FirstOrDefault(t => t.Id == id);
                if (x != null)
                    return View(x);
            }
            return RedirectToAction("List");
        }
        [HttpPost]
        public IActionResult Edit(CCommodityViewModel vm)
        {
            YoungArtistsContext db = new YoungArtistsContext();
            Commodity x = db.Commodities.FirstOrDefault(t => t.Id == vm.Id);
            if (x != null)
            {
                if (vm.photo != null)
                {
                    string fileExtension = System.IO.Path.GetExtension(vm.photo.FileName);
                    string photoName = Guid.NewGuid().ToString() + fileExtension;
                    string path = _environment.WebRootPath + "/Images/" + photoName;
                    x.CommodityImage = photoName;
                    vm.photo.CopyTo(new FileStream(path, FileMode.Create));
                }
                x.CommodityName = vm.CommodityName;
                x.CommodityNarrative = vm.CommodityNarrative;
                x.CommodityNum = vm.CommodityNum;
                //x.CommodityStart = vm.CommodityStart;
                x.CommodityPrice = vm.CommodityPrice;
                //x.CommodityImage = vm.CommodityImage;
                x.CommodityClassification = vm.CommodityClassification;
                x.CommodityState = vm.CommodityState;
                //db.Commodities.Add(x);
                db.SaveChangesAsync();
            }
            return RedirectToAction("List");
        }
        public IActionResult OnLine(int? id)
        {
            YoungArtistsContext db = new YoungArtistsContext();
            Commodity x = db.Commodities.FirstOrDefault(t => t.Id == id);
            if (x != null)
            {
                x.CommodityState = !x.CommodityState;
                db.SaveChangesAsync();
            }
            Debug.WriteLine("123");
            return RedirectToAction("List");
        }
        [HttpPost]
        public IActionResult BatchOnLine(string chkVal1)
        {
            YoungArtistsContext db = new YoungArtistsContext();
            if (chkVal1 != "")
            {
            List<int> idList = JsonConvert.DeserializeObject<List<int>>(chkVal1);
                for(int i =0;i<idList.Count;i++)
                {
                    Commodity x = db.Commodities.FirstOrDefault(t => t.Id == idList[i]);
                    if (x != null)
                    {
                        if ((bool)!x.CommodityState)
                        {

Young-Artists/Young-Artists/Views/Commodity/Index.cshtml
@model X.PagedList.IPagedList<Young_Artists.Models.Commodity>
@using X.PagedList;
@using X.PagedList.Mvc.Core;

@{
    ViewData["Title"] = "List";
}

<div class="pagetitle">
    <h1>商品清單</h1>
    <section class="section">
        <div class="row">
            <div class="col-lg-6">
            </div><!-- End Page Title -->

            <p>
                <a asp-action="Create" class="btn btn-primary">新增</a>
            </p>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            序
                            @Html.DisplayNameFor(model => model.FirstOrDefault().Id)
                            @Html.ActionLink("", "List", new { sortCommodity = "UpCommodityId" },new {Class="bi bi-caret-up-fill"})
                            @Html.ActionLink("", "List", new { sortCommodity = "DownCommodityId" },new {Class="bi bi-caret-down-fill"})
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityName)
                            @Html.ActionLink("", "List", new { sortCommodity = "UpCommodityName" },new {Class="bi bi-caret-up-fill"})
                            @Html.ActionLink("", "List", new { sortCommodity = "DownCommodityName" },new {Class="bi bi-caret-down-fill"})
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityNarrative)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityNum)
                            @Html.ActionLink("", "List", new { sortCommodity = "UpCommodityNum" },new {Class="bi bi-caret-up-fill"})
                            @Html.ActionLink("", "List", new { sortCommodity = "DownCommodityNum" },new {Class="bi bi-caret-down-fill"})

                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityPrice)
                            @Html.ActionLink("", "List", new { sortCommodity = "UpCommodityPrice" },new {Class="bi bi-caret-up-fill"})
                            @Html.ActionLink("", "List", new { sortCommodity = "DownCommodityPrice" },new {Class="bi bi-caret-down-fill"})
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityImage)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityStart)
                            @Html.ActionLink("", "List", new { sortCommodity = "UpCommodityStart" },new {Class="bi bi-caret-up-fill"})
                            @Html.ActionLink("", "List", new { sortCommodity = "DownCommodityStart" },new {Class="bi bi-caret-down-fill"})
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityClassification)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityState)
                            @Html.ActionLink("", "List", new { sortCommodity = "UpCommodityState" },new {Class="bi bi-caret-up-fill"})
                            @Html.ActionLink("", "List", new { sortCommodity = "DownCommodityState" },new {Class="bi bi-caret-down-fill"})
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int count = 0;
                        foreach (var item in Model)
                        {
                            count++;
                            <tr>
                                <td>
                                    @count
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CommodityName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CommodityNarrative)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CommodityNum)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CommodityPrice)
                                </td>
                                <td>
                                    <img src="~/Images/@item.CommodityImage" width="80" height="50" />
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CommodityStart)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CommodityClassification)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CommodityState)
                                </td>
                                <td>
                                    @Html.ActionLink("", "Edit", new { id=item.Id  },new{Class="btn btn-warning bi bi-brush text-white"})
                                    @Html.ActionLink("", "OnLine", new {  id=item.Id },new { Class = "btn btn-primary bi bi-arrow-down-up"})
                                    @Html.ActionLink("", "Delete","Commodity"
                            , new { id=item.Id },new {Class="btn btn-danger bi bi-trash3 text-white",onclick = "return confirm('確定要刪除嗎?')"})
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))

Young-Artists/Young-Artists/Views/Commodity/List.cshtml
@model X.PagedList.IPagedList<Young_Artists.Models.Commodity>
@using X.PagedList;
@using X.PagedList.Mvc.Core;

@{
    ViewData["Title"] = "List";
}
<script src="~/js/jquery-3.6.3.js"></script>
<link href="~/css/PagedList.css" rel="stylesheet" />
<div class="pagetitle">
    <h1>商品清單</h1>
    <section class="section">
        <div class="row">
            <div class="col-lg-6">
            </div><!-- End Page Title -->

            <p>
                <a asp-action="Create" class="btn btn-primary">新增</a>
            </p>
            <div style="display:flex">
                <div class="d-flex me-3">
                    <form action="@Url.Action("BatchOnLine", "Commodity")" method="post">
                        <input type="hidden" id="chkVal1" name="chkVal1">
                        <input type="submit" value="批量上架" class="btn btn-primary">
                    </form>
                </div>
                <div class="d-flex me-3">
                    <form action="@Url.Action("BatchOffLine", "Commodity")" method="post">
                        <input type="hidden" id="chkVal2" name="chkVal2">
                        <input type="submit" value="批量下架" class="btn btn-primary">
                    </form>
               </div>
                <div class="d-flex me-3">
                    <form action="@Url.Action("BatchDelect", "Commodity")" method="post">
                        <input type="hidden" id="chkVal3" name="chkVal3">
                        <input type="submit" value="批量刪除" class="btn btn-danger">
                    </form>
                </div>
            </div>

            @*<div>
                <input type="hidden" id="chkVal" name="chkVal">
                <form action="@Url.Action("BatchOnLine", "Commodity")" method="post">
                    <input type="hidden" name="chkVal">
                    <input type="submit" value="批量上架" class="btn btn-primary">
                </form>
                <form action="@Url.Action("BatchOffLine", "Commodity")" method="post">
                    <input type="hidden" name="chkVal">
                    <input type="submit" value="批量下架" class="btn btn-primary">
                </form>
                <form action="@Url.Action("BatchDelect", "Commodity")" method="post">
                    <input type="hidden" name="chkVal">
                    <input type="submit" value="批量刪除" class="btn btn-primary">
                </form>
            </div>*@
            @*<form>
                <input type="hidden" id="chkVal" name="chkVal">
                <input type="submit" value="批量上架" class="btn btn-primary" onclick="submitForm('BatchOnLine')">
                <input type="submit" value="批量下架" class="btn btn-primary" onclick="submitForm('BatchOffLine')">
                <input type="submit" value="批量刪除" class="btn btn-primary" onclick="submitForm('BatchDelect')">
            </form>*@
            
            <table class="table table-hover">
                <thead>
                    <input type="hidden" id="sort" name="sort">
                    <tr>
                        <th>
                            <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                <input id="btnCheckAll" type="checkbox" />
                                <span>全選</span>
                            </label>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().Id)
                            @Html.ActionLink("", "List", new { sortCommodity = "UpCommodityId" },new {Class="bi bi-caret-up-fill",onclick="setSortCommodity('UpCommodityId')"})
                            @Html.ActionLink("", "List", new { sortCommodity = "DownCommodityId" },new {Class="bi bi-caret-down-fill",onclick="setSortCommodity('DownCommodityId')"})
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityName)
                            @Html.ActionLink("", "List", new { sortCommodity = "UpCommodityName" },new {Class="bi bi-caret-up-fill",onclick="setSortCommodity('UpCommodityName')"})
                            @Html.ActionLink("", "List", new { sortCommodity = "DownCommodityName" },new {Class="bi bi-caret-down-fill",onclick="setSortCommodity('DownCommodityName')"})
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityNarrative)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityNum)
                            @Html.ActionLink("", "List", new { sortCommodity = "UpCommodityNum",@sortBy="UpCommodityNum" },new {Class="bi bi-caret-up-fill",onclick="setSortCommodity('UpCommodityNum')"})
                            @Html.ActionLink("", "List", new { sortCommodity = "DownCommodityNum",@sortBy="UpCommodityNum" },new {Class="bi bi-caret-down-fill",onclick="setSortCommodity('UpCommodityNum')"})

                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityPrice)
                            @Html.ActionLink("", "List", new { sortCommodity = "UpCommodityPrice" },new {Class="bi bi-caret-up-fill",onclick="setSortCommodity('UpCommodityPrice')"})
                            @Html.ActionLink("", "List", new { sortCommodity = "DownCommodityPrice" },new {Class="bi bi-caret-down-fill",onclick="setSortCommodity('DownCommodityPrice')"})
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityImage)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityStart)
                            @Html.ActionLink("", "List", new { sortCommodity = "UpCommodityStart" },new {Class="bi bi-caret-up-fill",onclick="setSortCommodity('UpCommodityStart')"})
                            @Html.ActionLink("", "List", new { sortCommodity = "DownCommodityStart" },new {Class="bi bi-caret-down-fill",onclick="setSortCommodity('DownCommodityStart')"})
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityClassification)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().CommodityState)
                            @Html.ActionLink("", "List", new { sortCommodity = "UpCommodityState" },new {Class="bi bi-caret-up-fill",onclick="setSortCommodity('UpCommodityState')"})
                            @Html.ActionLink("", "List", new { sortCommodity = "DownCommodityState" },new {Class="bi bi-caret-down-fill",onclick="setSortCommodity('DownCommodityState')"})
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <label>
                                        <input type="checkbox" name="ck" value="@item.Id"/>
                                    </label>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CommodityName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CommodityNarrative)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CommodityNum)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CommodityPrice)
                                </td>
                                <td>
                                    <img src="~/Images/@item.CommodityImage" width="80" height="50" />
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CommodityStart)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CommodityClassification)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CommodityState)
                                </td>
                                <td>
                                    @Html.ActionLink("", "Edit", new { id=item.Id  },new{Class="btn btn-warning bi bi-brush text-white"})
                                    @Html.ActionLink("", "OnLine", new {  id=item.Id },new { Class = "btn btn-primary bi bi-arrow-down-up"})
                                    @Html.ActionLink("", "Delete","Commodity", new { id=item.Id },new {Class="btn btn-danger bi bi-trash3 text-white",onclick = "return confirm('確定要刪除嗎?')"})
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            @Html.PagedListPager(Model, page => Url.Action("List", new {sortCommodity = ViewBag.sortBy, page }))
           
            <script>
                var sortType = "";
                let chkVal = [];
                $("#btnCheckAll").click(function () {
                    chkVal = [];
                    if ($("#btnCheckAll").prop("checked")) {
                        $("input[name='ck']").each(function () {
                            $(this).prop("checked", true);
                            chkVal.push($(this).val());
                        });
                    } else {
                        $("input[name='ck']").each(function () {
                            $(this).prop("checked", false);
                        });
                    }
                    console.log(chkVal);
                    $("#chkVal1").val(JSON.stringify(chkVal));
                    $("#chkVal2").val(JSON.stringify(chkVal));
                    $("#chkVal3").val(JSON.stringify(chkVal));
                });
                $("input[name='ck']").change(function () {
                    if ($(this).prop("checked")) {
                        chkVal.push($(this).val());
                    } else {
                        var index = chkVal.indexOf($(this).val());
                        if (index > -1) {
                            chkVal.splice(index, 1);
                        }
                    }
                    console.log(chkVal);
                    $("#chkVal1").val(JSON.stringify(chkVal));
                    $("#chkVal2").val(JSON.stringify(chkVal));
                    $("#chkVal3").val(JSON.stringify(chkVal));
                });
                //排序分頁保存資料
                function setSortCommodity(SortCommodity) {
                    $(".sort") = SortCommodity;
                    console.log(sortType);
                }
                //測試方法
                /*function setSortCommodity(sortType) {
                    $.ajax({
                        type: "GET",
                        url: "/Controller/Action?sortType=" + sortType,
                        success: function (data) {
                            // 在這裡更新頁面數據
                        }
                    });
                }
                */
            </script>
            